In [2]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data = pd.read_csv("data.csv")

In [6]:
data.head()

,Time End,Time End Local Tz,Time Offset,Time Start,Time Start Local Tz,User ID,Value
0,2019-05-05T09:40:00+03:00,2019-05-05T12:40:00+03:00,10800,2019-05-05T09:39:59+03:00,2019-05-05T12:39:59+03:00,2166,1.0
1,2019-05-05T11:13:29+03:00,2019-05-05T14:13:29+03:00,10800,2019-05-05T11:12:51+03:00,2019-05-05T14:12:51+03:00,2166,34.0
2,2019-05-05T12:07:42+03:00,2019-05-05T15:07:42+03:00,10800,2019-05-05T12:07:39+03:00,2019-05-05T15:07:39+03:00,2166,1.0
3,2019-05-05T13:04:05+03:00,2019-05-05T16:04:05+03:00,10800,2019-05-05T13:04:02+03:00,2019-05-05T16:04:02+03:00,2166,3.0
4,2019-05-05T13:18:18+03:00,2019-05-05T16:18:18+03:00,10800,2019-05-05T13:18:13+03:00,2019-05-05T16:18:13+03:00,2166,6.0

In [5]:
data["User ID"].unique()

array([2166])

In [7]:
data["Time Offset"].unique()

array([10800,  7200])

In [8]:
print(len(data[data["Time Offset"] == 10800]))

35986

In [9]:
print(len(data[data["Time Offset"] == 7200]))

3685

In [10]:
data.columns

Index(['Time End', 'Time End Local Tz', 'Time Offset', 'Time Start',
       'Time Start Local Tz', 'User ID', 'Value'],
      dtype='object')

In [61]:
data.head(35)

,Time End,Time End Local Tz,Time Offset,Time Start,Time Start Local Tz,User ID,Value
0,2019-05-05T09:40:00+03:00,2019-05-05T12:40:00+03:00,10800,2019-05-05T09:39:59+03:00,2019-05-05T12:39:59+03:00,2166,1.0
1,2019-05-05T11:13:29+03:00,2019-05-05T14:13:29+03:00,10800,2019-05-05T11:12:51+03:00,2019-05-05T14:12:51+03:00,2166,34.0
2,2019-05-05T12:07:42+03:00,2019-05-05T15:07:42+03:00,10800,2019-05-05T12:07:39+03:00,2019-05-05T15:07:39+03:00,2166,1.0
3,2019-05-05T13:04:05+03:00,2019-05-05T16:04:05+03:00,10800,2019-05-05T13:04:02+03:00,2019-05-05T16:04:02+03:00,2166,3.0
4,2019-05-05T13:18:18+03:00,2019-05-05T16:18:18+03:00,10800,2019-05-05T13:18:13+03:00,2019-05-05T16:18:13+03:00,2166,6.0
5,2019-05-05T14:59:59+03:00,2019-05-05T17:59:59+03:00,10800,2019-05-05T14:58:09+03:00,2019-05-05T17:58:09+03:00,2166,77.0
6,2019-05-05T17:12:35+03:00,2019-05-05T20:12:35+03:00,10800,2019-05-05T17:11:36+03:00,2019-05-05T20:11:36+03:00,2166,61.0
7,2019-05-05T17:21:00+03:00,2019-05-05T20:21:00+03:00,10800,2019-05-05T17:20:06+03:00,2019-05-05T20:20:06+03:00,2166,69.0
8,2019-05-05T17:35:48+03:00,2019-05-05T20:35:48+03:00,10800,2019-05-05T17:35:36+03:00,2019-05-05T20:35:36+03:00,2166,17.0
9,2019-05-05T18:03:48+03:00,2019-05-05T21:03:48+03:00,10800,2019-05-05T18:03:41+03:00,2019-05-05T21:03:41+03:00,2166,9.0
10,2019-05-05T19:02:10+03:00,2019-05-05T22:02:10+03:00,10800,2019-05-05T19:01:57+03:00,2019-05-05T22:01:57+03:00,2166,12.0
11,2019-06-05T06:49:42+03:00,2019-06-05T09:49:42+03:00,10800,2019-06-05T06:49:12+03:00,2019-06-05T09:49:12+03:00,2166,4.0
12,2019-06-05T06:53:38+03:00,2019-06-05T09:53:38+03:00,10800,2019-06-05T06:52:42+03:00,2019-06-05T09:52:42+03:00,2166,62.0
13,2019-06-05T07:08:29+03:00,2019-06-05T10:08:29+03:00,10800,2019-06-05T07:07:31+03:00,2019-06-05T10:07:31+03:00,2166,77.0
14,2019-06-05T10:56:04+03:00,2019-06-05T13:56:04+03:00,10800,2019-06-05T10:50:00+03:00,2019-06-05T13:50:00+03:00,2166,31.0
15,2019-06-05T11:09:59+03:00,2019-06-05T14:09:59+03:00,10800,2019-06-05T11:07:13+03:00,2019-06-05T14:07:13+03:00,2166,12.0
16,2019-06-05T11:28:19+03:00,2019-06-05T14:28:19+03:00,10800,2019-06-05T11:28:18+03:00,2019-06-05T14:28:18+03:00,2166,1.0
17,2019-06-05T11:59:37+03:00,2019-06-05T14:59:37+03:00,10800,2019-06-05T11:50:00+03:00,2019-06-05T14:50:00+03:00,2166,5.0
18,2019-06-05T13:59:41+03:00,2019-06-05T16:59:41+03:00,10800,2019-06-05T13:59:18+03:00,2019-06-05T16:59:18+03:00,2166,31.0
19,2019-06-05T14:40:38+03:00,2019-06-05T17:40:38+03:00,10800,2019-06-05T14:39:59+03:00,2019-06-05T17:39:59+03:00,2166,16.0
20,2019-06-05T16:09:18+03:00,2019-06-05T19:09:18+03:00,10800,2019-06-05T16:08:24+03:00,2019-06-05T19:08:24+03:00,2166,90.0
21,2019-06-05T16:16:28+03:00,2019-06-05T19:16:28+03:00,10800,2019-06-05T16:15:27+03:00,2019-06-05T19:15:27+03:00,2166,100.0
22,2019-06-05T17:12:38+03:00,2019-06-05T20:12:38+03:00,10800,2019-06-05T17:11:39+03:00,2019-06-05T20:11:39+03:00,2166,72.0
23,2019-06-05T17:25:31+03:00,2019-06-05T20:25:31+03:00,10800,2019-06-05T17:20:00+03:00,2019-06-05T20:20:00+03:00,2166,60.0
24,2019-06-05T17:30:00+03:00,2019-06-05T20:30:00+03:00,10800,2019-06-05T17:29:59+03:00,2019-06-05T20:29:59+03:00,2166,2.0
25,2019-06-05T17:53:39+03:00,2019-06-05T20:53:39+03:00,10800,2019-06-05T17:53:34+03:00,2019-06-05T20:53:34+03:00,2166,4.0
26,2019-06-05T19:38:46+03:00,2019-06-05T22:38:46+03:00,10800,2019-06-05T19:38:17+03:00,2019-06-05T22:38:17+03:00,2166,34.0
27,2019-06-05T19:39:50+03:00,2019-06-05T22:39:50+03:00,10800,2019-06-05T19:39:46+03:00,2019-06-05T22:39:46+03:00,2166,2.0
28,2019-06-05T20:08:07+03:00,2019-06-05T23:08:07+03:00,10800,2019-06-05T20:07:59+03:00,2019-06-05T23:07:59+03:00,2166,17.0
29,2019-06-05T20:15:22+03:00,2019-06-05T23:15:22+03:00,10800,2019-06-05T20:15:17+03:00,2019-06-05T23:15:17+03:00,2166,7.0
30,2019-06-05T20:33:41+03:00,2019-06-05T23:33:41+03:00,10800,2019-06-05T20:32:42+03:00,2019-06-05T23:32:42+03:00,2166,96.0
31,2019-06-05T20:38:42+03:00,2019-06-05T23:38:42+03:00,10800,2019-06-05T20:37:41+03:00,2019-06-05T23:37:41+03:00,2166,108.0
32,2019-06-05T20:41:38+03:00,2019-06-05T23:41:38+03:00,10800,2019-06-05T20:40:39+03:00,2019-06-05T23:40:39+03:00,2166,100.0
33,2019-06-05T20:59:59+03:00,2019-06-05T23:59:59+03:00,10800,2019-06-05T20:59:17+03:00,2019-06-05T23:59:17+03:00,2166,66.0
34,2019-07-16T07:31:12+03:00,2019-07-16T10:31:12+03:00,10800,2019-07-16T07:30:11+03:00,2019-07-16T10:30:11+03:00,2166,63.0

In [15]:
from datetime import datetime

In [44]:
index = 4
str_time_end = data.iloc[index]["Time End"]
str_time_start = data.iloc[index]["Time Start"]
print(str_time_start, str_time_end)

2019-05-05T13:18:13+03:00 2019-05-05T13:18:18+03:00

In [48]:
start_dt = datetime.strptime(str_time_start, "%Y-%m-%dT%H:%M:%S%z")
print(start_dt)
end_dt = datetime.strptime(str_time_end, "%Y-%m-%dT%H:%M:%S%z")
print(end_dt)

2019-05-05 13:18:13+03:00
2019-05-05 13:18:18+03:00

In [47]:
print(end_dt - start_dt)

0:00:05

In [56]:
index = 389
str_time_next = data.iloc[index+1]["Time Start"]
str_time_start = data.iloc[index]["Time Start"]
#print(str_time_start, str_time_next)

start_dt = datetime.strptime(str_time_start, "%Y-%m-%dT%H:%M:%S%z")
print(start_dt)
next_dt = datetime.strptime(str_time_next, "%Y-%m-%dT%H:%M:%S%z")
print(next_dt)

2019-07-07 07:10:59+03:00
2019-07-07 07:27:42+03:00

In [57]:
print(next_dt - start_dt)

0:16:43

In [71]:
data.iloc[38568]

Time End               2019-08-10T07:24:37+03:00
Time End Local Tz      2019-08-10T10:24:37+03:00
Time Offset                                10800
Time Start             2019-08-10T07:20:55+03:00
Time Start Local Tz    2019-08-10T10:20:55+03:00
User ID                                     2166
Value                                         99
datetime end           2019-08-10 07:24:37+03:00
Name: 38568, dtype: object

In [68]:
data7200 = data[data["Time Offset"] == 7200]
data7200

,Time End,Time End Local Tz,Time Offset,Time Start,Time Start Local Tz,User ID,Value,datetime end
389,2019-07-07T07:13:54+03:00,2019-07-07T09:13:54+03:00,7200,2019-07-07T07:10:59+03:00,2019-07-07T09:10:59+03:00,2166,39.0,2019-07-07 07:13:54+03:00
390,2019-07-07T07:29:59+03:00,2019-07-07T09:29:59+03:00,7200,2019-07-07T07:27:42+03:00,2019-07-07T09:27:42+03:00,2166,51.0,2019-07-07 07:29:59+03:00
391,2019-07-07T07:39:43+03:00,2019-07-07T09:39:43+03:00,7200,2019-07-07T07:38:44+03:00,2019-07-07T09:38:44+03:00,2166,47.0,2019-07-07 07:39:43+03:00
392,2019-07-07T07:55:28+03:00,2019-07-07T09:55:28+03:00,7200,2019-07-07T07:54:29+03:00,2019-07-07T09:54:29+03:00,2166,94.0,2019-07-07 07:55:28+03:00
393,2019-07-07T07:59:29+03:00,2019-07-07T09:59:29+03:00,7200,2019-07-07T07:58:53+03:00,2019-07-07T09:58:53+03:00,2166,40.0,2019-07-07 07:59:29+03:00
394,2019-07-07T07:59:52+03:00,2019-07-07T09:59:52+03:00,7200,2019-07-07T07:59:29+03:00,2019-07-07T09:59:29+03:00,2166,21.0,2019-07-07 07:59:52+03:00
395,2019-07-07T08:00:51+03:00,2019-07-07T10:00:51+03:00,7200,2019-07-07T07:59:59+03:00,2019-07-07T09:59:59+03:00,2166,69.0,2019-07-07 08:00:51+03:00
396,2019-07-07T08:02:41+03:00,2019-07-07T10:02:41+03:00,7200,2019-07-07T08:01:55+03:00,2019-07-07T10:01:55+03:00,2166,34.0,2019-07-07 08:02:41+03:00
397,2019-07-07T08:38:20+03:00,2019-07-07T10:38:20+03:00,7200,2019-07-07T08:37:07+03:00,2019-07-07T10:37:07+03:00,2166,14.0,2019-07-07 08:38:20+03:00
398,2019-07-07T08:45:18+03:00,2019-07-07T10:45:18+03:00,7200,2019-07-07T08:40:38+03:00,2019-07-07T10:40:38+03:00,2166,105.0,2019-07-07 08:45:18+03:00
399,2019-07-07T10:20:33+03:00,2019-07-07T12:20:33+03:00,7200,2019-07-07T10:20:12+03:00,2019-07-07T12:20:12+03:00,2166,19.0,2019-07-07 10:20:33+03:00
400,2019-07-07T11:08:49+03:00,2019-07-07T13:08:49+03:00,7200,2019-07-07T11:08:47+03:00,2019-07-07T13:08:47+03:00,2166,2.0,2019-07-07 11:08:49+03:00
401,2019-07-07T11:19:59+03:00,2019-07-07T13:19:59+03:00,7200,2019-07-07T11:18:30+03:00,2019-07-07T13:18:30+03:00,2166,2.0,2019-07-07 11:19:59+03:00
402,2019-07-07T12:20:30+03:00,2019-07-07T14:20:30+03:00,7200,2019-07-07T12:20:00+03:00,2019-07-07T14:20:00+03:00,2166,29.0,2019-07-07 12:20:30+03:00
403,2019-07-07T13:05:33+03:00,2019-07-07T15:05:33+03:00,7200,2019-07-07T13:04:34+03:00,2019-07-07T15:04:34+03:00,2166,84.0,2019-07-07 13:05:33+03:00
404,2019-07-07T13:05:38+03:00,2019-07-07T15:05:38+03:00,7200,2019-07-07T13:05:33+03:00,2019-07-07T15:05:33+03:00,2166,7.0,2019-07-07 13:05:38+03:00
405,2019-07-07T13:07:36+03:00,2019-07-07T15:07:36+03:00,7200,2019-07-07T13:06:37+03:00,2019-07-07T15:06:37+03:00,2166,66.0,2019-07-07 13:07:36+03:00
406,2019-07-07T13:11:31+03:00,2019-07-07T15:11:31+03:00,7200,2019-07-07T13:11:19+03:00,2019-07-07T15:11:19+03:00,2166,7.0,2019-07-07 13:11:31+03:00
407,2019-07-07T13:21:18+03:00,2019-07-07T15:21:18+03:00,7200,2019-07-07T13:20:37+03:00,2019-07-07T15:20:37+03:00,2166,3.0,2019-07-07 13:21:18+03:00
408,2019-07-07T13:53:55+03:00,2019-07-07T15:53:55+03:00,7200,2019-07-07T13:50:00+03:00,2019-07-07T15:50:00+03:00,2166,150.0,2019-07-07 13:53:55+03:00
409,2019-07-07T13:55:58+03:00,2019-07-07T15:55:58+03:00,7200,2019-07-07T13:54:59+03:00,2019-07-07T15:54:59+03:00,2166,84.0,2019-07-07 13:55:58+03:00
410,2019-07-07T13:56:57+03:00,2019-07-07T15:56:57+03:00,7200,2019-07-07T13:55:58+03:00,2019-07-07T15:55:58+03:00,2166,96.0,2019-07-07 13:56:57+03:00
411,2019-07-07T13:58:55+03:00,2019-07-07T15:58:55+03:00,7200,2019-07-07T13:57:56+03:00,2019-07-07T15:57:56+03:00,2166,30.0,2019-07-07 13:58:55+03:00
412,2019-07-07T14:12:52+03:00,2019-07-07T16:12:52+03:00,7200,2019-07-07T14:12:38+03:00,2019-07-07T16:12:38+03:00,2166,21.0,2019-07-07 14:12:52+03:00
413,2019-07-07T14:14:11+03:00,2019-07-07T16:14:11+03:00,7200,2019-07-07T14:13:35+03:00,2019-07-07T16:13:35+03:00,2166,56.0,2019-07-07 14:14:11+03:00
414,2019-07-07T14:34:23+03:00,2019-07-07T16:34:23+03:00,7200,2019-07-07T14:30:00+03:00,2019-07-07T16:30:00+03:00,2166,444.0,2019-07-07 14:34:23+03:00
415,2019-07-07T14:38:23+03:00,2019-07-07T16:38:23+03:00,7200,2019-07-07T14:37:19+03:00,2019-07-07T16:37:19+03:00,2166,97.0,2019-07-07 14:38:23+03:00
416,2019-07-07T14:39:59+03:00,2019-07-07T16:39:59+03:00,7200,2019-07-07T14:39:25+03:00,2019-07-07T16:39:25+03:00,2166,120.0,2019-07-07 14:39:59+03:00
417,2019-07-07T14:40:00+03:00,2019-07-07T16:40:00+03:00,7200,2019-07-07T14:39:59+03:00,2019-07-07T16:39:59+03:00,2166,2.0,2019-07-07 14:40:00+03:00
418,2019-07-07T14:49:31+03:00,2019-07-07T16:49:31+03:00,7200,2019-07-07T14:41:56+03:00,2019-07-07T16:41:56+03:00,2166,37.0,2019-07-07 14:49:31+03:00
...,...,...,...,...,...,...,...,...
38538,2019-07-03T12:51:02+03:00,2019-07-03T14:51:02+03:00,7200,2019-07-03T12:50:24+03:00,2019-07-03T14:50:24+03:00,2166,35.0,2019-07-03 12:51:02+03:00
38539,2019-07-03T13:06:32+03:00,2019-07-03T15:06:32+03:00,7200,2019-07-03T13:05:44+03:00,2019-07-03T15:05:44+03:00,2166,33.0,2019-07-03 13:06:32+03:00
38540,2019-07-03T14:06:25+03:00,2019-07-03T16:06:25+03:00,7200,2019-07-03T14:05:41+03:00,2019-07-03T16:05:41+03:00,2166,28.0,2019-07-03 14:06:25+03:00
38541,2019-07-03T14:26:19+03:00,2019-07-03T16:26:19+03:00,7200,2019-07-03T14:25:20+03:00,2019-07-03T16:25:20+03:00,2166,77.0,2019-07-03 14:26:19+03:00
38542,2019-07-03T15:00:04+03:00,2019-07-03T17:00:04+03:00,7200,2019-07-03T14:59:59+03:00,2019-07-03T16:59:59+03:00,2166,7.0,2019-07-03 15:00:04+03:00
38543,2019-07-03T15:02:23+03:00,2019-07-03T17:02:23+03:00,7200,2019-07-03T15:01:26+03:00,2019-07-03T17:01:26+03:00,2166,85.0,2019-07-03 15:02:23+03:00
38544,2019-07-03T15:02:27+03:00,2019-07-03T17:02:27+03:00,7200,2019-07-03T15:02:25+03:00,2019-07-03T17:02:25+03:00,2166,2.0,2019-07-03 15:02:27+03:00
38545,2019-07-03T15:18:05+03:00,2019-07-03T17:18:05+03:00,7200,2019-07-03T15:17:17+03:00,2019-07-03T17:17:17+03:00,2166,26.0,2019-07-03 15:18:05+03:00
38546,2019-07-03T15:23:41+03:00,2019-07-03T17:23:41+03:00,7200,2019-07-03T15:22:42+03:00,2019-07-03T17:22:42+03:00,2166,57.0,2019-07-03 15:23:41+03:00
38547,2019-07-03T16:00:00+03:00,2019-07-03T18:00:00+03:00,7200,2019-07-03T15:59:59+03:00,2019-07-03T17:59:59+03:00,2166,1.0,2019-07-03 16:00:00+03:00
38548,2019-07-03T17:09:51+03:00,2019-07-03T19:09:51+03:00,7200,2019-07-03T17:08:34+03:00,2019-07-03T19:08:34+03:00,2166,47.0,2019-07-03 17:09:51+03:00
38549,2019-07-03T17:13:42+03:00,2019-07-03T19:13:42+03:00,7200,2019-07-03T17:13:03+03:00,2019-07-03T19:13:03+03:00,2166,31.0,2019-07-03 17:13:42+03:00
38550,2019-07-03T17:19:11+03:00,2019-07-03T19:19:11+03:00,7200,2019-07-03T17:18:59+03:00,2019-07-03T19:18:59+03:00,2166,5.0,2019-07-03 17:19:11+03:00
38551,2019-07-03T17:24:17+03:00,2019-07-03T19:24:17+03:00,7200,2019-07-03T17:23:33+03:00,2019-07-03T19:23:33+03:00,2166,15.0,2019-07-03 17:24:17+03:00
38552,2019-07-03T17:34:28+03:00,2019-07-03T19:34:28+03:00,7200,2019-07-03T17:34:26+03:00,2019-07-03T19:34:26+03:00,2166,1.0,2019-07-03 17:34:28+03:00
38553,2019-07-03T18:22:28+03:00,2019-07-03T20:22:28+03:00,7200,2019-07-03T18:21:32+03:00,2019-07-03T20:21:32+03:00,2166,30.0,2019-07-03 18:22:28+03:00
38554,2019-07-03T18:28:42+03:00,2019-07-03T20:28:42+03:00,7200,2019-07-03T18:27:43+03:00,2019-07-03T20:27:43+03:00,2166,96.0,2019-07-03 18:28:42+03:00
38555,2019-07-03T18:34:36+03:00,2019-07-03T20:34:36+03:00,7200,2019-07-03T18:33:37+03:00,2019-07-03T20:33:37+03:00,2166,95.0,2019-07-03 18:34:36+03:00
38556,2019-07-03T18:39:59+03:00,2019-07-03T20:39:59+03:00,7200,2019-07-03T18:39:04+03:00,2019-07-03T20:39:04+03:00,2166,81.0,2019-07-03 18:39:59+03:00
38557,2019-07-03T18:41:41+03:00,2019-07-03T20:41:41+03:00,7200,2019-07-03T18:41:02+03:00,2019-07-03T20:41:02+03:00,2166,54.0,2019-07-03 18:41:41+03:00
38558,2019-07-03T18:43:03+03:00,2019-07-03T20:43:03+03:00,7200,2019-07-03T18:42:04+03:00,2019-07-03T20:42:04+03:00,2166,86.0,2019-07-03 18:43:03+03:00
38559,2019-07-03T18:48:58+03:00,2019-07-03T20:48:58+03:00,7200,2019-07-03T18:48:00+03:00,2019-07-03T20:48:00+03:00,2166,95.0,2019-07-03 18:48:58+03:00
38560,2019-07-03T18:54:57+03:00,2019-07-03T20:54:57+03:00,7200,2019-07-03T18:54:37+03:00,2019-07-03T20:54:37+03:00,2166,23.0,2019-07-03 18:54:57+03:00
38561,2019-07-03T19:12:26+03:00,2019-07-03T21:12:26+03:00,7200,2019-07-03T19:11:27+03:00,2019-07-03T21:11:27+03:00,2166,41.0,2019-07-03 19:12:26+03:00
38562,2019-07-03T19:19:16+03:00,2019-07-03T21:19:16+03:00,7200,2019-07-03T19:18:04+03:00,2019-07-03T21:18:04+03:00,2166,100.0,2019-07-03 19:19:16+03:00
38563,2019-07-03T19:24:35+03:00,2019-07-03T21:24:35+03:00,7200,2019-07-03T19:24:10+03:00,2019-07-03T21:24:10+03:00,2166,36.0,2019-07-03 19:24:35+03:00
38564,2019-07-03T19:29:59+03:00,2019-07-03T21:29:59+03:00,7200,2019-07-03T19:29:05+03:00,2019-07-03T21:29:05+03:00,2166,90.0,2019-07-03 19:29:59+03:00
38565,2019-07-03T19:34:30+03:00,2019-07-03T21:34:30+03:00,7200,2019-07-03T19:34:07+03:00,2019-07-03T21:34:07+03:00,2166,33.0,2019-07-03 19:34:30+03:00
38566,2019-07-03T19:39:59+03:00,2019-07-03T21:39:59+03:00,7200,2019-07-03T19:39:57+03:00,2019-07-03T21:39:57+03:00,2166,1.0,2019-07-03 19:39:59+03:00
38567,2019-07-03T19:42:59+03:00,2019-07-03T21:42:59+03:00,7200,2019-07-03T19:42:31+03:00,2019-07-03T21:42:31+03:00,2166,25.0,2019-07-03 19:42:59+03:00

In [58]:
data["Time Offset"].dtype

dtype('int64')

In [62]:
data.head()

,Time End,Time End Local Tz,Time Offset,Time Start,Time Start Local Tz,User ID,Value
0,2019-05-05T09:40:00+03:00,2019-05-05T12:40:00+03:00,10800,2019-05-05T09:39:59+03:00,2019-05-05T12:39:59+03:00,2166,1.0
1,2019-05-05T11:13:29+03:00,2019-05-05T14:13:29+03:00,10800,2019-05-05T11:12:51+03:00,2019-05-05T14:12:51+03:00,2166,34.0
2,2019-05-05T12:07:42+03:00,2019-05-05T15:07:42+03:00,10800,2019-05-05T12:07:39+03:00,2019-05-05T15:07:39+03:00,2166,1.0
3,2019-05-05T13:04:05+03:00,2019-05-05T16:04:05+03:00,10800,2019-05-05T13:04:02+03:00,2019-05-05T16:04:02+03:00,2166,3.0
4,2019-05-05T13:18:18+03:00,2019-05-05T16:18:18+03:00,10800,2019-05-05T13:18:13+03:00,2019-05-05T16:18:13+03:00,2166,6.0

In [64]:
data["datetime end"] = pd.to_datetime(data["Time End"])

In [65]:
data.head()

,Time End,Time End Local Tz,Time Offset,Time Start,Time Start Local Tz,User ID,Value,datetime end
0,2019-05-05T09:40:00+03:00,2019-05-05T12:40:00+03:00,10800,2019-05-05T09:39:59+03:00,2019-05-05T12:39:59+03:00,2166,1.0,2019-05-05 09:40:00+03:00
1,2019-05-05T11:13:29+03:00,2019-05-05T14:13:29+03:00,10800,2019-05-05T11:12:51+03:00,2019-05-05T14:12:51+03:00,2166,34.0,2019-05-05 11:13:29+03:00
2,2019-05-05T12:07:42+03:00,2019-05-05T15:07:42+03:00,10800,2019-05-05T12:07:39+03:00,2019-05-05T15:07:39+03:00,2166,1.0,2019-05-05 12:07:42+03:00
3,2019-05-05T13:04:05+03:00,2019-05-05T16:04:05+03:00,10800,2019-05-05T13:04:02+03:00,2019-05-05T16:04:02+03:00,2166,3.0,2019-05-05 13:04:05+03:00
4,2019-05-05T13:18:18+03:00,2019-05-05T16:18:18+03:00,10800,2019-05-05T13:18:13+03:00,2019-05-05T16:18:13+03:00,2166,6.0,2019-05-05 13:18:18+03:00

In [66]:
data["datetime end"].dtype

datetime64[ns, pytz.FixedOffset(180)]